---
# This workflow uses actions that are not certified by GitHub. They are provided
# by a third-party and are governed by separate terms of service, privacy
# policy, and support documentation.

name: "ðŸŽ¯ Step: Upload to S3 by platform"
on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      package-version:
        required: true
        type: string

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-upload
  cancel-in-progress: true

# Variables available to all jobs defined in this file
env:
  DOCKER_BUILDKIT: 1
  REGISTRY: ${{ vars.REGISTRY }}

# Declare default permissions as read only.
permissions: read-all

jobs:
  upload_ubuntu:
    runs-on: ubuntu-latest
    name: ðŸŽ¯ Upload to S3
    strategy:
      fail-fast: false
      matrix:
        release:
          - name: focal
          - name: jammy
        arch:
          - id: amd64
          - id: arm64

    container:
      image: ghcr.io/northwood-labs/package-builder/ubuntu-v22.04:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      options: --privileged

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Being paranoid
        run: |
          echo "package-name: ${{ inputs.package-name }}"
          echo "package-version: ${{ inputs.package-version }}"
          echo "release-name: ${{ matrix.release.name }}"
          echo "cpu-arch: ${{ matrix.arch.id }}"

      - name: Restore the cached packages from the previous stage
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        id: cache
        with:
          key: "${{ inputs.package-name }}-${{ inputs.package-version }}-ubuntu-${{ matrix.release.name }}-${{ matrix.arch.id }}"
          path: packages/${{ inputs.package-name }}/dist

      - name: Perform upload to S3
        working-directory: packages/${{ inputs.package-name }}/dist
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWSSSEKMSID: "${{ secrets.AWSSSEKMSID }}"
          PACKAGE_BUCKET: ${{ vars.PACKAGE_BUCKET }}
        run: |
          if [[ -f $(find . -maxdepth 1 -type f -name "${{ inputs.package-name }}_*_arm64.deb") ]]; then
            aws s3 cp ${{ inputs.package-name }}_*_arm64.deb s3://${PACKAGE_BUCKET}/apt/pool/${{ matrix.release.name }}/
          fi
          if [[ -f $(find . -maxdepth 1 -type f -name "${{ inputs.package-name }}_*_amd64.deb") ]]; then
            aws s3 cp ${{ inputs.package-name }}_*_amd64.deb s3://${PACKAGE_BUCKET}/apt/pool/${{ matrix.release.name }}/
          fi
